<?php

use Detain\Cloudlinux\Cloudlinux;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-05-31 at 10:07:32.
 */
class CloudlinuxTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Cloudlinux
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new Cloudlinux(getenv('CLOUDLINUX_LOGIN'), getenv('CLOUDLINUX_KEY'));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::getcurlpage
	 * @todo   Implement testLog().
	 */
	public function testGetcurlpage()
	{
		$this->assertRegExp('/<html/i', $this->object->getcurlpage('https://cln.cloudlinux.com'));
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::log
	 * @todo   Implement testLog().
	 */
	public function testLog()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::status
	 * @todo   Implement testStatus().
	 */
	public function testStatus()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::availability
	 * @todo   Implement testAvailability().
	 */
	public function testAvailability()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::check
	 * @todo   Implement testCheck().
	 */
	public function testCheck()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::register
	 * @todo   Implement testRegister().
	 */
	public function testRegister()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::rest_remove
	 * @todo   Implement testRest_remove().
	 */
	public function testRest_remove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::remove
	 * @todo   Implement testRemove().
	 */
	public function testRemove()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::rest_list
	 * @todo   Implement testRest_list().
	 */
	public function testRest_list()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::authToken
	 * @todo   Implement testAuthToken().
	 */
	public function testAuthToken()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::license
	 * @todo   Implement testLicense().
	 */
	public function testLicense()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::remove_license
	 * @todo   Implement testRemove_license().
	 */
	public function testRemove_license()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::is_licensed
	 * @todo   Implement testIs_licensed().
	 */
	public function testIs_licensed()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::xml_is_licensed
	 * @todo   Implement testXml_is_licensed().
	 */
	public function testXml_is_licensed()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::license_list
	 * @todo   Implement testLicense_list().
	 */
	public function testLicense_list()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\Cloudlinux\Cloudlinux::reconcile
	 * @todo   Implement testReconcile().
	 */
	public function testReconcile()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
