---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Design/TooManyPublicMethods:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.php"
exclude_paths:
- tests/
