env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
language: php
os: linux
dist: trusty
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
 
before_script:
  - mkdir -p build/logs
  - pear install pear/XML_RPC2
  - phpenv rehash
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: 
  - vendor/phpunit/phpunit/phpunit --bootstrap tests/bootstrap.php tests/CloudlinuxTest.php -v --debug --coverage-clover build/logs/clover.xml
  - set
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then vendor/bin/test-reporter --exit-code $TRAVIS_TEST_RESULT; fi
