language: php
os: linux
dist: trusty
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly
 
before_script:
  - pear install pear/XML_RPC2
  - phpenv rehash
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: vendor/phpunit/phpunit/phpunit --bootstrap tests/bootstrap.php tests/CloudlinuxTest.php -v --debug
